[project]
name = "tf-mcp-server"
version = "0.1.0"
description = "Terraform Drift Detection MCP Server"
dependencies = [
    "fastapi",
    "uvicorn",
    "fastmcp",  # make sure it's installable or replace with correct import source
]

[tool.setuptools]
packages = ["tf_mcp_server"]